### ISSUE TITLE
ElevenLabs TTS Sounds like Chipmunks when using OPUS

### ISSUE THREAD

**Issue by lylepratt** [jambonz/freeswitch-modules#12]
Connect to a call that is using ElevenLabs TTS and OPUS codec and you'll notice the tts is garbled and sounds like chipmunks.

**Comment by lylepratt** [comment]
FYI the same problem exists with G722. Seems like its audio rate problem. FS doesn't know its getting back 8k audio.

**Comment by davehorton** [comment]
yep, we are going to be working on this

**Comment by xquanluu** [comment]
Hi @lylepratt 

above PR should fix the issue, could you please give it a try?
