### ISSUE TITLE
mod_audio_fork supports play audio stream

### ISSUE THREAD

**Issue by xquanluu** [jambonz/freeswitch-modules#25]
add new feature to mod_audio_fork, which is support for bi-directional streaming audio.  Currently the far end can send us base64 encoded audio and we save it, write it to a file, and then play the file.  We should keep that feature, but add a new option where they send us linear 16 pcm audio and we stream it out immediately using the same SBF_WRITE_REPLACE thing we do in mod_dub.

**Comment by davehorton** [comment]
merged
