### ISSUE TITLE
mod_google_transcribe does not signal grpc internal error

### ISSUE THREAD

**Issue by ajgolledge** [jambonz/freeswitch-modules#26]
It is possible that the `grpc_read_thread` function in `mod_google_transcribe/google_glue_v1.cpp` and in `mod_google_transcribe/google_glue_v2.cpp` exits without the FreeSWITCH client being aware of this. We experienced an example of this where we experienced an internal grpc error. This is what the logs looked like:
```
2024-03-14 21:34:20.675689 99.83% [DEBUG] google_glue_v2.cpp:281 grpc_read_thread: got 1 responses
2024-03-14 21:35:41.755685 99.87% [DEBUG] google_glue_v2.cpp:296 grpc_read_thread: finish() status Internal error encountered. (13)
```
The nature of the error is still mysterious and we have not been able to reproduce it but the problem could occur with any status code returned from the `streamer->finish()` call in `grpc_read_thread` which does not equal 11 in the case of `google_glue_v1.cpp` and 10 in the case of `google_glue_v2.cpp`. In the case of the internal error detailed in the log output above, the status code was 13 which meant that no event was fired and the client received no indication that the `grpc_read_thread` function was no longer running. The only indication of a problem was in the FreeSWITCH logs.
The client should receive some kind of an event in a case like this. Although the example above is rare and difficult to reproduce it could potentially occur when other status error codes are returned from `streamer->finish()`.

**Comment by davehorton** [comment]
merged
