### ISSUE TITLE
Add Support for Deepgram Text-to-speech (TTS) to library

### ISSUE THREAD

**Issue by jpvajda** [jambonz/freeswitch-modules#30]
Similar to the support for Deepgram audio transcription (STT) you see[ here. ](https://github.com/jambonz/freeswitch-modules/tree/main/mod_deepgram_transcribe). We like to request the maintainers of the project also add support for Deepgram TTS in a similar way. 

## Implementation References

* https://developers.deepgram.com/reference/text-to-speech-api
* https://developers.deepgram.com/docs/text-to-speech

**Comment by jpvajda** [comment]
@davehorton @ajgolledge  @xquanluu  👋 Deepgram would be interested in paying you for this addition and we could sponsor this GH project for a 1 time donation of $500 if you could help us add this feature.  Just let me know if that is something you'd be interested in. 

Thanks for the consideration.

cc @dvonthenen

**Comment by davehorton** [comment]
@jpvajda yes we are interested in adding support for Deepgram streaming TTS in here.  Feel free to sponsor us [here](https://github.com/sponsors/drachtio).  Can we contact you directly if we have any questions during the implementation?

**Comment by xquanluu** [comment]
Hi @jpvajda 

I have created a PR for support deepgram TTS in freeswitch modules, however this need to be reviewed by @davehorton ,

I already posted a question on deepgram discord but have not received any response yet. The question is:

This Freeswitch module is asking deepgram tts for PCM linear16 8000hz

At the begining of each downloaded audio file, there is a short 20 ms audio that has a strange sound like the sound when we searching channel in a radio.

This issue happens even if I use curl command to download the audio for any string of text.

**Comment by jpvajda** [comment]
@xquanluu  let me find that message in Discord, I'll reach out. Thanks for the PR to review. I'll check that out as well.

**Comment by jpvajda** [comment]
@xquanluu @davehorton  i noticed this module is lacking in Documentation a bit, could you provide a similar set of instructions like you did for the transcription [Module?](https://github.com/jambonz/freeswitch-modules/blob/main/mod_deepgram_transcribe/README.md) A [Readme](https://github.com/jambonz/freeswitch-modules/blob/main/mod_deepgram_transcribe/README.md) like this would be really helpful.

**Comment by davehorton** [comment]
merged
