### ISSUE TITLE
Google speech to text en-IN does not work through transcribe

### ISSUE THREAD

**Issue by vasudevan-Kore** [jambonz/freeswitch-modules#6]
when we set en-IN as the language for google ASR, it does not give transcriptions. en-US works. Our assumption is enhanced model is being set to true by default in transcribe. This could be tested through transcribe and setting language to en-IN

**Comment by xquanluu** [comment]
Hi @vasudevan-Kore 

Could you please use different model for en-IN

for example 

```
transcribe: {
          transcriptionHook: '/dial-time/transcribe',
          recognizer: {
            vendor: 'default',
            language: 'en-IN',
            separateRecognitionPerChannel: true,
            enhancedModel: false,
            model: 'telephony'
          },
        },
```

**Comment by xquanluu** [comment]
I'm closing this issue as it's not valid bug from jambonz.
