### ISSUE TITLE
call identifiers in start message of transcribe with custom speech API

### ISSUE THREAD

**Issue by vasudevan-Kore** [jambonz/freeswitch-modules#82]
Hi Jambonz Team

Currently we build some custom speech vendor integrations we are having hard time in debugging the issues related to a call, adding additional info related to call identifiers so we can debug the issues. https://www.jambonz.org/docs/supporting-articles/custom-speech-stt/ adding callSid any additional info in the start message helps.

**Comment by vdharashive** [comment]
This is implementation @vasudevan-Kore close the ticket
