### ISSUE TITLE
Feat: Deepgram TTS support for on-premise 

### ISSUE THREAD

**Issue by vdharashive** [jambonz/freeswitch-modules#93]
as it support asr URL for on-premise similar URL , similar option for TTS need to be support , each should have its own endpoint

**Comment by vdharashive** [comment]
@xquanluu i can provide endpoint for testing

**Comment by xquanluu** [comment]
Hi @vdharashive  Deepgram transcribe module already support this feature. Please use recognizer.deepgramOptions 

{
deepgramSttUri: string;
deepgramSttUseTls: boolean;
}

**Comment by xquanluu** [comment]
My bad this ticket is fore deepgram on TTS

**Comment by vdharashive** [comment]
We tested it , its working fine

**Comment by vdharashive** [comment]
@xquanluu @davehorton pls mege this

**Comment by vdharashive** [comment]
Thanks @xquanluu
