### ISSUE TITLE
Deepgram TTS integration

### ISSUE THREAD

**Issue by Gowtham-Pulkaram** [jambonz/freeswitch-modules#96]
Hi,

I am unable to proceed further with deepgram tts.
How do I convert the text-to-speech with this module as I can't find any API or APP to start text-to-speech?
Please provide a Document on this module. 

Note: The module compiled and loaded successfully but there is no documentation on how to use this module....

Please help!!!!!!

Thanks

**Comment by davehorton** [comment]
this module is intended for use with jambonz, external docs not available at this time
